### PR TITLE
change name

### PR DESCRIPTION
**Pull request by pfi79**

### CODE REVIEW

**Review by HagarMeir — APPROVED** [review]

**Comment by HagarMeir** [comment]
@pfi79 can you please update this also in fabric?

**Comment by pfi79** [comment]
> @pfi79 can you please update this also in fabric?

Yeah, I'm doing that right now.

**Comment by HagarMeir** [comment]
https://github.com/hyperledger/fabric/pull/4750

sorry but we would like to have it today
so already started working on it earlier
just have some issues I need to solve

**Comment by pfi79** [comment]
> [hyperledger/fabric#4750](https://github.com/hyperledger/fabric/pull/4750)
> 
> sorry but we would like to have it today so already started working on it earlier just have some issues I need to solve

I'm sorry, it's not up to me. I'm waiting for the fabric library to accept my change. Then it'll work.
https://github.com/hyperledger/fabric-lib-go/pull

If you can help with that, that would be great.

**Comment by HagarMeir** [comment]
Ah ok thanks

**Pull request merged**
